### ISSUE TITLE
Windows Path-Seperator

### ISSUE THREAD

**Issue by Sfletche132** [saucer/saucer-cli#2]
Hi,

I've tried to embed a simple react project with shadcn/tailwind css into an executable.

When I run the embed command it results in the below header which will not compile:

```cpp
#pragma once
#include <map>
#include <string>
#include <saucer/webview.hpp>

#include "assets\index-39437b50.css.hpp"
#include "assets\index-99cf2deb.js.hpp"
#include "assets\react-35ef61ed.svg.hpp"
#include "index.html.hpp"
#include "vite.svg.hpp"

namespace saucer::embedded
{
    inline auto all()
    {
        std::map<std::string, embedded_file> rtn;

        rtn.emplace("assets\index-39437b50.css", embedded_file{"text/css", assets_index______b___css});
        rtn.emplace("assets\index-99cf2deb.js", embedded_file{"application/javascript", assets_index___cf_deb_js});
        rtn.emplace("assets\react-35ef61ed.svg", embedded_file{"image/svg+xml", assets_react___ef__ed_svg});
        rtn.emplace("index.html", embedded_file{"text/html", index_html});
        rtn.emplace("vite.svg", embedded_file{"image/svg+xml", vite_svg});

        return rtn;
    }
} // namespace saucer::embedded
```

I'm using visual studio 2022 on windows 10 within vscode.

**Comment by Curve** [comment]
Oh, the windows paths use backslashes, seems I must've missed that when dealing with edge cases.

Will look into it right now

**Comment by Sfletche132** [comment]
> Oh, the windows paths use backslashes, seems I must've missed that when dealing with edge cases.
> 
> Will look into it right now

That's great thanks! Feel free to close the duplicated issue, mistake on my part.

**Comment by Curve** [comment]
@Sfletche132 I've just published an update (it's not yet quite done, I still want to refactor large portions of the cli-code but should be ready to be used), could you check if that works for you?

**Comment by Curve** [comment]
Just tested this in a VM and seems to be fixed

**Comment by Sfletche132** [comment]
I've tested it and it's working on my machine!

**Comment by Curve** [comment]
> I've tested it and it's working on my machine!

Good to hear!
