### ISSUE TITLE
braces are not closed in generated all.hpp

### ISSUE THREAD

**Issue by leoyoung07** [saucer/saucer-cli#4]
syntax error in generated `all.hpp` ,  braces are not closed:

![image](https://github.com/saucer/saucer-cli/assets/8199708/55d7259c-fa72-4c51-83f7-5407fe1cbc39)

`saucer-app` version: 4.2.1

embed  command: `saucer embed build include/embedded`

**Comment by Curve** [comment]
Fixed ^^
