### ISSUE TITLE
Numbers in filenames

### ISSUE THREAD

**Issue by ColoredCarrot** [saucer/saucer-cli#5]
Currently, while numbers in filenames stay for the generated `.hpp` filenames (`file-1.txt` becomes `file-1.txt.hpp`), this is not true for the generated C++.
In the generated variable names, numbers are replaced by underscores, e.g. `file___txt`.

This leads to duplicated variable names when, e.g., you have a bunch of `image-1.jpg`, `image-2.jpg`, etc. from a CMS.

It would be great if numbers were kept as-is in variable names (except leading numbers might have to be prefixed with something).

A separate idea, maybe as a CLI option, would be to just base62-encode filenames for variable names.
This would completely prevent ambiguous variable names, at the cost of making them unreadable to humans.

What do you think?
If you agree, I can submit a PR to implement (either or both approaches)

**Comment by Curve** [comment]
> This would completely prevent ambiguous variable names, at the cost of making them unreadable to humans.

I like this idea, the variable names aren't really supposed to be used by humans anyways so this could be an option.

I'll also consider some alternatives _(There used to be an implementation that prevented duplicate file names by keeping track of all names and appending numbers in case there were clashes which I seem to have forgotten to port while rewriting the CLI)_

**Comment by ColoredCarrot** [comment]
That sounds like a good solution as well!

Also, thinking about it a bit more, the way it is currently allows multiple consecutive underscores, which I believe is technically UB in C++ (anything containing `__` or beginning with `_` + a capital letter is a reserved identifier).
So technically, double underscores should be escaped as well

**Comment by Curve** [comment]
> That sounds like a good solution as well!
> 
> Also, thinking about it a bit more, the way it is currently allows multiple consecutive underscores, which I believe is technically UB in C++ (anything containing `__` or beginning with `_` + a capital letter is a reserved identifier).
> So technically, double underscores should be escaped as well

iirc this only concerns double scores at the beginning of the name

**Comment by ColoredCarrot** [comment]
Nope, anywhere in the name unfortunately.
> Identifiers that appear as a token or preprocessing token (i.e., not in user-defined-string-literal like operator ""id)(since C++11) of one of the following forms are reserved:
> - in the global namespace, identifiers that begin with an underscore
> - identifiers that contain a double underscore or begin with an underscore followed by an uppercase letter [...]

https://en.cppreference.com/w/cpp/language/identifiers#In_declarations

**Comment by Curve** [comment]
> Nope, anywhere in the name unfortunately.
> > Identifiers that appear as a token or preprocessing token (i.e., not in user-defined-string-literal like operator ""id)(since C++11) of one of the following forms are reserved:
> > - in the global namespace, identifiers that begin with an underscore
> > - identifiers that contain a double underscore or begin with an underscore followed by an uppercase letter [...]
> 
> https://en.cppreference.com/w/cpp/language/identifiers#In_declarations

Oh, thanks for the heads up ^^!

**Comment by Curve** [comment]
Went with the base62 approach as it was the nicest of the bunch, thanks for bringing this up!

**Comment by ColoredCarrot** [comment]
Great! Thank you for resolving so quickly :)

**Comment by Curve** [comment]
> Great! Thank you for resolving so quickly :)

Thank you for all the issue reports lately :)
